### ISSUE TITLE
Event handler is not removed

### ISSUE THREAD

**Issue by locks** [mtmckenna/croissant-hoops#1]
Possible memory leak in https://github.com/mtmckenna/croissant-hoops/blob/master/src/ui/components/croissant-hoops/component.ts#L25 because the handler is never removed.

**Comment by mtmckenna** [comment]
Thank you for pointing this out! In [this commit](https://github.com/mtmckenna/croissant-hoops/commit/ed86020b44852a728ac321de4205691542ca37ef), I removed the event listener in the `willDestroy` hook. I think that should do it. Thank you again, and please let me know if you notice anything else! =)
